const UI = {
  MOBILE_BREAKPOINT: 500,
  TABLET_BREAKPOINT: 715,
  DESKTOP_BREAKPOINT: 1100,
  MAX_CONTENT_WIDTH: 1300,
  PAGE_CONTAINED_PADDING_VW: 5,

  HEADER_HEIGHT_PX: 75,

  Z_INDEX_PAGE_LOADER: 33333,
  Z_INDEX_MODAL_OVERLAY: 1033,
};

export default UI;
