export const USERS = {
	LOGGEDIN: 			'USER_LOGGEDIN',
	TOKEN: 				'USER_TOKEN',
	EMAIL: 				'USER_EMAIL',
	LASTLOGGEDIN: 		'USER_LASTLOGGEDIN',
	TRADINGS_BUY: 		'USER_TRADINGS_BUY', 
	TRADINGS_SELL: 		'USER_TRADINGS_SELL', 
	TRADINGS_TOTAL: 	'USER_TRADINGS_TOTAL', 
	ACCOUNT_DEPOSIT: 	'USER_ACCOUNT_DEPOSIT', 
	ACCOUNT_WITHDRAW: 	'USER_ACCOUNT_WITHDRAW', 
	ACCOUNT_CURRENT: 	'USER_ACCOUNT_CURRENT',
	ACCOUNT_TOTAL: 		'USER_ACCOUNT_TOTAL', 
	VERIFIED: 			'USER_VERIFIED', 
	DATA_RESET: 		'DATA_RESET',
}

export const COMPANYINFO = {
	TOTAL_SALES: 		'TOTAL_SALES',
	TOTAL_REVENUE:      'TOTAL_REVENUE',
	TOTAL_COST: 		'TOTAL_COST',
	TOTAL_PROFIT: 		'TOTAL_PROFIT'
}

export const COMPANYCALENDAR = {
	ALL_EVENTS : 		'ALL_EVENTS',
	NEW_EVENT: 			'NEW_EVENT',
	DELETE_EVENT: 		'DELETE_EVENT',
	EDIT_EVENT: 		'EDIT_EVENT',

	ALL_TASKS : 		'ALL_TASKS',
	NEW_TASK: 			'NEW_TASK',
	DELETE_TASK: 		'DELETE_TASK',
	EDIT_TASK: 			'EDIT_TASK',

	ALL_ORDERS : 		'ALL_ORDERS',
	NEW_ORDER: 			'NEW_ORDER',
	DELETE_ORDER: 		'DELETE_ORDER',
	EDIT_ORDER: 		'EDIT_ORDER',
}
export const THEMEOPTIONS = {
	MENU_TOGGLER: 'MENU_TOGGLER',
	MENU_OPEN: 'MENU_OPEN'
}