const initState = [
	{
		ID: 1928372,
		from: 'team@elementor.com',
		isSeen: 0,
		name: 'Elementor',
		subject: 'Introducing Elementor Experts - Discover Leading Web Creators',
		desc: '<div class="p-0 p-sm-5" style="text-align:center; border: 1px solid rgba(220, 220, 220, 0.3); background: rgba(233, 233, 233, 0.3); border-radius: 3px"><h2>Vurox Admin React Theme</h2><h5 style="padding: 0 50px;font-weight:300">Vurox is an amazing theme for bootstrapping new websites for analytics, product management, traffic source checking, you can checkout our new demos and template features from here and there</h5><img src="/image/campaign.png" style="max-width:100%" alt="" /> <p> <a href="" style="padding: 10px 20px;font-size: 16px;text-transform: uppercase;background: rgba(0,0,0,0.5);color: #ddd;font-weight: 700;height: 60px;display: inline-block;line-height: 43px;width: 240px;border-radius: 3px;">Check out more</a> </p></div>',
		time: '23-03-2020 08:23PM',
	},
	{
		ID: 19283763,
		from: 'noreply@edm.warriorforum.com',
		isSeen: 0,
		name: 'Warrior Forum',
		subject: 'Searching for some great guides? Working from home?',
		desc: '<div class="p-0 p-sm-5" style="text-align:center; border: 1px solid rgba(220, 220, 220, 0.3); background: rgba(233, 233, 233, 0.3); border-radius: 3px"><h2>Vurox Admin React Theme</h2><h5 style="padding: 0 50px;font-weight:300">Vurox is an amazing theme for bootstrapping new websites for analytics, product management, traffic source checking, you can checkout our new demos and template features from here and there</h5><img src="/image/campaign.png" style="max-width:100%" alt="" /> <p> <a href="" style="padding: 10px 20px;font-size: 16px;text-transform: uppercase;background: rgba(0,0,0,0.5);color: #ddd;font-weight: 700;height: 60px;display: inline-block;line-height: 43px;width: 240px;border-radius: 3px;">Check out more</a> </p></div>',
		time: '22-03-2020 08:23PM',
	},
	{
		ID: 19283764,
		from: 'noreply@team360.com',
		isSeen: 0,
		name: 'Team 360',
		subject: 'Meet 🌿 Nature Illustrations!',
		desc: '<div class="p-0 p-sm-5" style="text-align:center; border: 1px solid rgba(220, 220, 220, 0.3); background: rgba(233, 233, 233, 0.3); border-radius: 3px"><h2>Vurox Admin React Theme</h2><h5 style="padding: 0 50px;font-weight:300">Vurox is an amazing theme for bootstrapping new websites for analytics, product management, traffic source checking, you can checkout our new demos and template features from here and there</h5><img src="/image/campaign.png" style="max-width:100%" alt="" /> <p> <a href="" style="padding: 10px 20px;font-size: 16px;text-transform: uppercase;background: rgba(0,0,0,0.5);color: #ddd;font-weight: 700;height: 60px;display: inline-block;line-height: 43px;width: 240px;border-radius: 3px;">Check out more</a> </p></div>',
		time: '21-03-2020 08:23PM',
	},
	{
		ID: 19283765,
		from: 'noreply@unbounce.com',
		isSeen: 1,
		name: 'unbounce',
		subject: 'You got Afterclap Demo Illustration!',
		desc: '<div class="p-0 p-sm-5" style="text-align:center; border: 1px solid rgba(220, 220, 220, 0.3); background: rgba(233, 233, 233, 0.3); border-radius: 3px"><h2>Vurox Admin React Theme</h2><h5 style="padding: 0 50px;font-weight:300">Vurox is an amazing theme for bootstrapping new websites for analytics, product management, traffic source checking, you can checkout our new demos and template features from here and there</h5><img src="/image/campaign.png" style="max-width:100%" alt="" /> <p> <a href="" style="padding: 10px 20px;font-size: 16px;text-transform: uppercase;background: rgba(0,0,0,0.5);color: #ddd;font-weight: 700;height: 60px;display: inline-block;line-height: 43px;width: 240px;border-radius: 3px;">Check out more</a> </p></div>',
		time: '20-03-2020 08:23PM',
	},
	{
		ID: 19283766,
		from: 'noreply@admim.kit.com',
		isSeen: 1,
		name: 'admim Kit',
		subject: '💪 Let’s keep on inspiring each other!',
		desc: '<div class="p-0 p-sm-5" style="text-align:center; border: 1px solid rgba(220, 220, 220, 0.3); background: rgba(233, 233, 233, 0.3); border-radius: 3px"><h2>Vurox Admin React Theme</h2><h5 style="padding: 0 50px;font-weight:300">Vurox is an amazing theme for bootstrapping new websites for analytics, product management, traffic source checking, you can checkout our new demos and template features from here and there</h5><img src="/image/campaign.png" style="max-width:100%" alt="" /> <p> <a href="" style="padding: 10px 20px;font-size: 16px;text-transform: uppercase;background: rgba(0,0,0,0.5);color: #ddd;font-weight: 700;height: 60px;display: inline-block;line-height: 43px;width: 240px;border-radius: 3px;">Check out more</a> </p></div>',
		time: '19-03-2020 08:23PM',
	},
	{
		ID: 19283767,
		from: 'noreply@nodejs.com',
		isSeen: 1,
		name: 'Nodejs',
		subject: 'How To Rank #1 on Google, According to Rand Fishkin, Co-Founder of Moz',
		desc: '<div class="p-0 p-sm-5" style="text-align:center; border: 1px solid rgba(220, 220, 220, 0.3); background: rgba(233, 233, 233, 0.3); border-radius: 3px"><h2>Vurox Admin React Theme</h2><h5 style="padding: 0 50px;font-weight:300">Vurox is an amazing theme for bootstrapping new websites for analytics, product management, traffic source checking, you can checkout our new demos and template features from here and there</h5><img src="/image/campaign.png" style="max-width:100%" alt="" /> <p> <a href="" style="padding: 10px 20px;font-size: 16px;text-transform: uppercase;background: rgba(0,0,0,0.5);color: #ddd;font-weight: 700;height: 60px;display: inline-block;line-height: 43px;width: 240px;border-radius: 3px;">Check out more</a> </p></div>',
		time: '18-03-2020 08:23PM',
	},
	{
		ID: 19283768,
		from: 'noreply@stripe.com',
		isSeen: 1,
		name: 'Stripe',
		subject: 'Discover Now: Writing for Inner Calm, Live Events, and More',
		desc: '<div class="p-0 p-sm-5" style="text-align:center; border: 1px solid rgba(220, 220, 220, 0.3); background: rgba(233, 233, 233, 0.3); border-radius: 3px"><h2>Vurox Admin React Theme</h2><h5 style="padding: 0 50px;font-weight:300">Vurox is an amazing theme for bootstrapping new websites for analytics, product management, traffic source checking, you can checkout our new demos and template features from here and there</h5><img src="/image/campaign.png" style="max-width:100%" alt="" /> <p> <a href="" style="padding: 10px 20px;font-size: 16px;text-transform: uppercase;background: rgba(0,0,0,0.5);color: #ddd;font-weight: 700;height: 60px;display: inline-block;line-height: 43px;width: 240px;border-radius: 3px;">Check out more</a> </p></div>',
		time: '17-03-2020 08:23PM',
	},
	{
		ID: 19283769,
		from: 'noreply@popcorn.com',
		isSeen: 1,
		name: 'Popcorn',
		subject: 'Introducing New Fund to Support Photographers',
		desc: '<div class="p-0 p-sm-5" style="text-align:center; border: 1px solid rgba(220, 220, 220, 0.3); background: rgba(233, 233, 233, 0.3); border-radius: 3px"><h2>Vurox Admin React Theme</h2><h5 style="padding: 0 50px;font-weight:300">Vurox is an amazing theme for bootstrapping new websites for analytics, product management, traffic source checking, you can checkout our new demos and template features from here and there</h5><img src="/image/campaign.png" style="max-width:100%" alt="" /> <p> <a href="" style="padding: 10px 20px;font-size: 16px;text-transform: uppercase;background: rgba(0,0,0,0.5);color: #ddd;font-weight: 700;height: 60px;display: inline-block;line-height: 43px;width: 240px;border-radius: 3px;">Check out more</a> </p></div>',
		time: '16-03-2020 08:23PM',
	},
	{
		ID: 19283770,
		from: 'noreply@slack.com',
		isSeen: 1,
		name: 'Slack',
		subject: '🏘Mobile Renting App UIs + 📆Calendar App Challenge',
		desc: '<div class="p-0 p-sm-5" style="text-align:center; border: 1px solid rgba(220, 220, 220, 0.3); background: rgba(233, 233, 233, 0.3); border-radius: 3px"><h2>Vurox Admin React Theme</h2><h5 style="padding: 0 50px;font-weight:300">Vurox is an amazing theme for bootstrapping new websites for analytics, product management, traffic source checking, you can checkout our new demos and template features from here and there</h5><img src="/image/campaign.png" style="max-width:100%" alt="" /> <p> <a href="" style="padding: 10px 20px;font-size: 16px;text-transform: uppercase;background: rgba(0,0,0,0.5);color: #ddd;font-weight: 700;height: 60px;display: inline-block;line-height: 43px;width: 240px;border-radius: 3px;">Check out more</a> </p></div>',
		time: '15-03-2020 08:23PM',
	},
	{
		ID: 19283771,
		from: 'noreply@webdesign.com',
		isSeen: 1,
		name: 'Webdesign',
		subject: '👨‍⚕️Helpful Health App Designs and more',
		desc: '<div class="p-0 p-sm-5" style="text-align:center; border: 1px solid rgba(220, 220, 220, 0.3); background: rgba(233, 233, 233, 0.3); border-radius: 3px"><h2>Vurox Admin React Theme</h2><h5 style="padding: 0 50px;font-weight:300">Vurox is an amazing theme for bootstrapping new websites for analytics, product management, traffic source checking, you can checkout our new demos and template features from here and there</h5><img src="/image/campaign.png" style="max-width:100%" alt="" /> <p> <a href="" style="padding: 10px 20px;font-size: 16px;text-transform: uppercase;background: rgba(0,0,0,0.5);color: #ddd;font-weight: 700;height: 60px;display: inline-block;line-height: 43px;width: 240px;border-radius: 3px;">Check out more</a> </p></div>',
		time: '14-03-2020 04:20PM',
	},
	{
		ID: 19283772,
		from: 'noreply@webflow.com',
		isSeen: 1,
		name: 'Webflow',
		subject: 'mBehavior Basic - New Free FCPX Plugin 🔥',
		desc: '<div class="p-0 p-sm-5" style="text-align:center; border: 1px solid rgba(220, 220, 220, 0.3); background: rgba(233, 233, 233, 0.3); border-radius: 3px"><h2>Vurox Admin React Theme</h2><h5 style="padding: 0 50px;font-weight:300">Vurox is an amazing theme for bootstrapping new websites for analytics, product management, traffic source checking, you can checkout our new demos and template features from here and there</h5><img src="/image/campaign.png" style="max-width:100%" alt="" /> <p> <a href="" style="padding: 10px 20px;font-size: 16px;text-transform: uppercase;background: rgba(0,0,0,0.5);color: #ddd;font-weight: 700;height: 60px;display: inline-block;line-height: 43px;width: 240px;border-radius: 3px;">Check out more</a> </p></div>',
		time: '13-03-2020 08:21PM',
	},
	{
		ID: 19283773,
		from: 'noreply@craftwork.com',
		isSeen: 1,
		name: 'Craftwork',
		subject: 'Announcing our global craftwork Festival 🎉',
		desc: '<div class="p-0 p-sm-5" style="text-align:center; border: 1px solid rgba(220, 220, 220, 0.3); background: rgba(233, 233, 233, 0.3); border-radius: 3px"><h2>Vurox Admin React Theme</h2><h5 style="padding: 0 50px;font-weight:300">Vurox is an amazing theme for bootstrapping new websites for analytics, product management, traffic source checking, you can checkout our new demos and template features from here and there</h5><img src="/image/campaign.png" style="max-width:100%" alt="" /> <p> <a href="" style="padding: 10px 20px;font-size: 16px;text-transform: uppercase;background: rgba(0,0,0,0.5);color: #ddd;font-weight: 700;height: 60px;display: inline-block;line-height: 43px;width: 240px;border-radius: 3px;">Check out more</a> </p></div>',
		time: '12-03-2020 02:23PM',
	},
	{
		ID: 19283774,
		from: 'noreply@photopea.com',
		isSeen: 1,
		name: 'Photopea',
		subject: 'Answering the Web’s Most Searched Marketing Questions | Geraint Clarke in Better Marketing',
		desc: '<div class="p-0 p-sm-5" style="text-align:center; border: 1px solid rgba(220, 220, 220, 0.3); background: rgba(233, 233, 233, 0.3); border-radius: 3px"><h2>Vurox Admin React Theme</h2><h5 style="padding: 0 50px;font-weight:300">Vurox is an amazing theme for bootstrapping new websites for analytics, product management, traffic source checking, you can checkout our new demos and template features from here and there</h5><img src="/image/campaign.png" style="max-width:100%" alt="" /> <p> <a href="" style="padding: 10px 20px;font-size: 16px;text-transform: uppercase;background: rgba(0,0,0,0.5);color: #ddd;font-weight: 700;height: 60px;display: inline-block;line-height: 43px;width: 240px;border-radius: 3px;">Check out more</a> </p></div>',
		time: '11-03-2020 03:23PM',
	},
	{
		ID: 19283775,
		from: 'noreply@okmonk.com',
		isSeen: 1,
		name: 'Okmonk',
		subject: 'How to set up your remote design process? Read best practices!',
		desc: '<div class="p-0 p-sm-5" style="text-align:center; border: 1px solid rgba(220, 220, 220, 0.3); background: rgba(233, 233, 233, 0.3); border-radius: 3px"><h2>Vurox Admin React Theme</h2><h5 style="padding: 0 50px;font-weight:300">Vurox is an amazing theme for bootstrapping new websites for analytics, product management, traffic source checking, you can checkout our new demos and template features from here and there</h5><img src="/image/campaign.png" style="max-width:100%" alt="" /> <p> <a href="" style="padding: 10px 20px;font-size: 16px;text-transform: uppercase;background: rgba(0,0,0,0.5);color: #ddd;font-weight: 700;height: 60px;display: inline-block;line-height: 43px;width: 240px;border-radius: 3px;">Check out more</a> </p></div>',
		time: '10-03-2020 05:23PM',
	},
	{
		ID: 19283776,
		from: 'noreply@renderforest.com',
		isSeen: 1,
		name: 'Render Forest',
		subject: 'ENDING SOON: 25% Off Flash Sale',
		desc: '<div class="p-0 p-sm-5" style="text-align:center; border: 1px solid rgba(220, 220, 220, 0.3); background: rgba(233, 233, 233, 0.3); border-radius: 3px"><h2>Vurox Admin React Theme</h2><h5 style="padding: 0 50px;font-weight:300">Vurox is an amazing theme for bootstrapping new websites for analytics, product management, traffic source checking, you can checkout our new demos and template features from here and there</h5><img src="/image/campaign.png" style="max-width:100%" alt="" /> <p> <a href="" style="padding: 10px 20px;font-size: 16px;text-transform: uppercase;background: rgba(0,0,0,0.5);color: #ddd;font-weight: 700;height: 60px;display: inline-block;line-height: 43px;width: 240px;border-radius: 3px;">Check out more</a> </p></div>',
		time: '23-10-2019 08:23PM',
	},
	{
		ID: 19283777,
		from: 'noreply@crello.com',
		isSeen: 1,
		name: 'Crello',
		subject: 'Your Complete Digital Marketing Strategy for 2020 | Elna Cain in Better Marketing',
		desc: '<div class="p-0 p-sm-5" style="text-align:center; border: 1px solid rgba(220, 220, 220, 0.3); background: rgba(233, 233, 233, 0.3); border-radius: 3px"><h2>Vurox Admin React Theme</h2><h5 style="padding: 0 50px;font-weight:300">Vurox is an amazing theme for bootstrapping new websites for analytics, product management, traffic source checking, you can checkout our new demos and template features from here and there</h5><img src="/image/campaign.png" style="max-width:100%" alt="" /> <p> <a href="" style="padding: 10px 20px;font-size: 16px;text-transform: uppercase;background: rgba(0,0,0,0.5);color: #ddd;font-weight: 700;height: 60px;display: inline-block;line-height: 43px;width: 240px;border-radius: 3px;">Check out more</a> </p></div>',
		time: '23-10-2019 08:23PM',
	},
	{
		ID: 19283778,
		from: 'noreply@collectui.com',
		isSeen: 1,
		name: 'Collect ui',
		subject: 'Book Delivery! Hot Right Now 2020 & Superpowers of PWAs',
		desc: '<div class="p-0 p-sm-5" style="text-align:center; border: 1px solid rgba(220, 220, 220, 0.3); background: rgba(233, 233, 233, 0.3); border-radius: 3px"><h2>Vurox Admin React Theme</h2><h5 style="padding: 0 50px;font-weight:300">Vurox is an amazing theme for bootstrapping new websites for analytics, product management, traffic source checking, you can checkout our new demos and template features from here and there</h5><img src="/image/campaign.png" style="max-width:100%" alt="" /> <p> <a href="" style="padding: 10px 20px;font-size: 16px;text-transform: uppercase;background: rgba(0,0,0,0.5);color: #ddd;font-weight: 700;height: 60px;display: inline-block;line-height: 43px;width: 240px;border-radius: 3px;">Check out more</a> </p></div>',
		time: '23-10-2019 08:23PM',
	},
	{
		ID: 19283779,
		from: 'noreply@uigoodies.com',
		isSeen: 1,
		name: 'UI Goodies',
		subject: 'Advanced New Highlight Recovery - Photo RAW 2020.1',
		desc: '<div class="p-0 p-sm-5" style="text-align:center; border: 1px solid rgba(220, 220, 220, 0.3); background: rgba(233, 233, 233, 0.3); border-radius: 3px"><h2>Vurox Admin React Theme</h2><h5 style="padding: 0 50px;font-weight:300">Vurox is an amazing theme for bootstrapping new websites for analytics, product management, traffic source checking, you can checkout our new demos and template features from here and there</h5><img src="/image/campaign.png" style="max-width:100%" alt="" /> <p> <a href="" style="padding: 10px 20px;font-size: 16px;text-transform: uppercase;background: rgba(0,0,0,0.5);color: #ddd;font-weight: 700;height: 60px;display: inline-block;line-height: 43px;width: 240px;border-radius: 3px;">Check out more</a> </p></div>',
		time: '23-10-2019 08:23PM',
	},
	{
		ID: 19283780,
		from: 'noreply@land-book.com',
		isSeen: 1,
		name: 'Land-book',
		subject: 'The best photos of work from home life',
		desc: '<div class="p-0 p-sm-5" style="text-align:center; border: 1px solid rgba(220, 220, 220, 0.3); background: rgba(233, 233, 233, 0.3); border-radius: 3px"><h2>Vurox Admin React Theme</h2><h5 style="padding: 0 50px;font-weight:300">Vurox is an amazing theme for bootstrapping new websites for analytics, product management, traffic source checking, you can checkout our new demos and template features from here and there</h5><img src="/image/campaign.png" style="max-width:100%" alt="" /> <p> <a href="" style="padding: 10px 20px;font-size: 16px;text-transform: uppercase;background: rgba(0,0,0,0.5);color: #ddd;font-weight: 700;height: 60px;display: inline-block;line-height: 43px;width: 240px;border-radius: 3px;">Check out more</a> </p></div>',
		time: '23-10-2019 08:23PM',
	},
	{
		ID: 19283781,
		from: 'noreply@lapa.ninja.com',
		isSeen: 1,
		name: 'Lapa Ninja',
		subject: 'Over 750K downloads in 24 hours',
		desc: '<div class="p-0 p-sm-5" style="text-align:center; border: 1px solid rgba(220, 220, 220, 0.3); background: rgba(233, 233, 233, 0.3); border-radius: 3px"><h2>Vurox Admin React Theme</h2><h5 style="padding: 0 50px;font-weight:300">Vurox is an amazing theme for bootstrapping new websites for analytics, product management, traffic source checking, you can checkout our new demos and template features from here and there</h5><img src="/image/campaign.png" style="max-width:100%" alt="" /> <p> <a href="" style="padding: 10px 20px;font-size: 16px;text-transform: uppercase;background: rgba(0,0,0,0.5);color: #ddd;font-weight: 700;height: 60px;display: inline-block;line-height: 43px;width: 240px;border-radius: 3px;">Check out more</a> </p></div>',
		time: '23-10-2019 08:23PM',
	},
	{
		ID: 19283782,
		from: 'noreply@elegantthemes.com',
		isSeen: 1,
		name: 'Elegant Themes',
		subject: 'Your Exclusive Welcome Gift is Still Waiting for You',
		desc: '<div class="p-0 p-sm-5" style="text-align:center; border: 1px solid rgba(220, 220, 220, 0.3); background: rgba(233, 233, 233, 0.3); border-radius: 3px"><h2>Vurox Admin React Theme</h2><h5 style="padding: 0 50px;font-weight:300">Vurox is an amazing theme for bootstrapping new websites for analytics, product management, traffic source checking, you can checkout our new demos and template features from here and there</h5><img src="/image/campaign.png" style="max-width:100%" alt="" /> <p> <a href="" style="padding: 10px 20px;font-size: 16px;text-transform: uppercase;background: rgba(0,0,0,0.5);color: #ddd;font-weight: 700;height: 60px;display: inline-block;line-height: 43px;width: 240px;border-radius: 3px;">Check out more</a> </p></div>',
		time: '23-10-2019 08:23PM',
	},
	{
		ID: 19283783,
		from: 'noreply@helpscout.com',
		isSeen: 1,
		name: 'Helpscout',
		subject: 'You Only Focus On Growth (Not Retention) Marketing? | Felicia C. Sullivan in Marketing Made Simple',
		desc: '<div class="p-0 p-sm-5" style="text-align:center; border: 1px solid rgba(220, 220, 220, 0.3); background: rgba(233, 233, 233, 0.3); border-radius: 3px"><h2>Vurox Admin React Theme</h2><h5 style="padding: 0 50px;font-weight:300">Vurox is an amazing theme for bootstrapping new websites for analytics, product management, traffic source checking, you can checkout our new demos and template features from here and there</h5><img src="/image/campaign.png" style="max-width:100%" alt="" /> <p> <a href="" style="padding: 10px 20px;font-size: 16px;text-transform: uppercase;background: rgba(0,0,0,0.5);color: #ddd;font-weight: 700;height: 60px;display: inline-block;line-height: 43px;width: 240px;border-radius: 3px;">Check out more</a> </p></div>',
		time: '23-10-2019 08:23PM',
	},
	{
		ID: 19283784,
		from: 'noreply@mixpanel.com',
		isSeen: 1,
		name: 'Mixpanel',
		subject: 'Ibn Battuta - Escape to China - Extra History - #4, I need a team?, Professional game designers',
		desc: '<div class="p-0 p-sm-5" style="text-align:center; border: 1px solid rgba(220, 220, 220, 0.3); background: rgba(233, 233, 233, 0.3); border-radius: 3px"><h2>Vurox Admin React Theme</h2><h5 style="padding: 0 50px;font-weight:300">Vurox is an amazing theme for bootstrapping new websites for analytics, product management, traffic source checking, you can checkout our new demos and template features from here and there</h5><img src="/image/campaign.png" style="max-width:100%" alt="" /> <p> <a href="" style="padding: 10px 20px;font-size: 16px;text-transform: uppercase;background: rgba(0,0,0,0.5);color: #ddd;font-weight: 700;height: 60px;display: inline-block;line-height: 43px;width: 240px;border-radius: 3px;">Check out more</a> </p></div>',
		time: '23-10-2019 08:23PM',
	},
	{
		ID: 19283785,
		from: 'noreply@evrybo.com',
		isSeen: 1,
		name: 'Evrybo',
		subject: 'Want A Trial? Try Our Sponsored SMM Panel!',
		desc: '<div class="p-0 p-sm-5" style="text-align:center; border: 1px solid rgba(220, 220, 220, 0.3); background: rgba(233, 233, 233, 0.3); border-radius: 3px"><h2>Vurox Admin React Theme</h2><h5 style="padding: 0 50px;font-weight:300">Vurox is an amazing theme for bootstrapping new websites for analytics, product management, traffic source checking, you can checkout our new demos and template features from here and there</h5><img src="/image/campaign.png" style="max-width:100%" alt="" /> <p> <a href="" style="padding: 10px 20px;font-size: 16px;text-transform: uppercase;background: rgba(0,0,0,0.5);color: #ddd;font-weight: 700;height: 60px;display: inline-block;line-height: 43px;width: 240px;border-radius: 3px;">Check out more</a> </p></div>',
		time: '23-10-2019 08:23PM',
	},
	{
		ID: 19283786,
		from: 'noreply@netguru.com',
		isSeen: 1,
		name: 'Netguru',
		subject: 'Digital transformation of the world’s largest real estate franchise',
		desc: '<div class="p-0 p-sm-5" style="text-align:center; border: 1px solid rgba(220, 220, 220, 0.3); background: rgba(233, 233, 233, 0.3); border-radius: 3px"><h2>Vurox Admin React Theme</h2><h5 style="padding: 0 50px;font-weight:300">Vurox is an amazing theme for bootstrapping new websites for analytics, product management, traffic source checking, you can checkout our new demos and template features from here and there</h5><img src="/image/campaign.png" style="max-width:100%" alt="" /> <p> <a href="" style="padding: 10px 20px;font-size: 16px;text-transform: uppercase;background: rgba(0,0,0,0.5);color: #ddd;font-weight: 700;height: 60px;display: inline-block;line-height: 43px;width: 240px;border-radius: 3px;">Check out more</a> </p></div>',
		time: '23-10-2019 08:23PM',
	},
	{
		ID: 19283787,
		from: 'noreply@ueno.com',
		isSeen: 1,
		name: 'Ueno',
		subject: 'Designing and building beautiful digital products, brands, and experiences',
		desc: '<div class="p-0 p-sm-5" style="text-align:center; border: 1px solid rgba(220, 220, 220, 0.3); background: rgba(233, 233, 233, 0.3); border-radius: 3px"><h2>Vurox Admin React Theme</h2><h5 style="padding: 0 50px;font-weight:300">Vurox is an amazing theme for bootstrapping new websites for analytics, product management, traffic source checking, you can checkout our new demos and template features from here and there</h5><img src="/image/campaign.png" style="max-width:100%" alt="" /> <p> <a href="" style="padding: 10px 20px;font-size: 16px;text-transform: uppercase;background: rgba(0,0,0,0.5);color: #ddd;font-weight: 700;height: 60px;display: inline-block;line-height: 43px;width: 240px;border-radius: 3px;">Check out more</a> </p></div>',
		time: '23-10-2019 08:23PM',
	},
	{
		ID: 19283788,
		from: 'noreply@wearetane.com',
		isSeen: 1,
		name: 'Wearetane',
		subject: 'Digital ad campaigns or OTT advertising, planning serves',
		desc: '<div class="p-0 p-sm-5" style="text-align:center; border: 1px solid rgba(220, 220, 220, 0.3); background: rgba(233, 233, 233, 0.3); border-radius: 3px"><h2>Vurox Admin React Theme</h2><h5 style="padding: 0 50px;font-weight:300">Vurox is an amazing theme for bootstrapping new websites for analytics, product management, traffic source checking, you can checkout our new demos and template features from here and there</h5><img src="/image/campaign.png" style="max-width:100%" alt="" /> <p> <a href="" style="padding: 10px 20px;font-size: 16px;text-transform: uppercase;background: rgba(0,0,0,0.5);color: #ddd;font-weight: 700;height: 60px;display: inline-block;line-height: 43px;width: 240px;border-radius: 3px;">Check out more</a> </p></div>',
		time: '23-10-2019 08:23PM',
	},
	{
		ID: 19283789,
		from: 'noreply@accord-aca.com',
		isSeen: 1,
		name: 'Accord',
		subject: 'Affordable Care Act compliance is not easy! Our software improves the reporting process',
		desc: '<div class="p-0 p-sm-5" style="text-align:center; border: 1px solid rgba(220, 220, 220, 0.3); background: rgba(233, 233, 233, 0.3); border-radius: 3px"><h2>Vurox Admin React Theme</h2><h5 style="padding: 0 50px;font-weight:300">Vurox is an amazing theme for bootstrapping new websites for analytics, product management, traffic source checking, you can checkout our new demos and template features from here and there</h5><img src="/image/campaign.png" style="max-width:100%" alt="" /> <p> <a href="" style="padding: 10px 20px;font-size: 16px;text-transform: uppercase;background: rgba(0,0,0,0.5);color: #ddd;font-weight: 700;height: 60px;display: inline-block;line-height: 43px;width: 240px;border-radius: 3px;">Check out more</a> </p></div>',
		time: '23-10-2019 08:23PM',
	},
	{
		ID: 19283790,
		from: 'noreply@buddy.works.com',
		isSeen: 1,
		name: 'Buddy Works',
		subject: 'Buddy is the most effective way to build better apps faster',
		desc: '<div class="p-0 p-sm-5" style="text-align:center; border: 1px solid rgba(220, 220, 220, 0.3); background: rgba(233, 233, 233, 0.3); border-radius: 3px"><h2>Vurox Admin React Theme</h2><h5 style="padding: 0 50px;font-weight:300">Vurox is an amazing theme for bootstrapping new websites for analytics, product management, traffic source checking, you can checkout our new demos and template features from here and there</h5><img src="/image/campaign.png" style="max-width:100%" alt="" /> <p> <a href="" style="padding: 10px 20px;font-size: 16px;text-transform: uppercase;background: rgba(0,0,0,0.5);color: #ddd;font-weight: 700;height: 60px;display: inline-block;line-height: 43px;width: 240px;border-radius: 3px;">Check out more</a> </p></div>',
		time: '23-10-2019 08:23PM',
	},
	{
		ID: 19283791,
		from: 'noreply@signals.network.com',
		isSeen: 1,
		name: 'Signals Network',
		subject: '📌 Conversational english, English vocabulary words and 12 other boards like yours',
		desc: '<div class="p-0 p-sm-5" style="text-align:center; border: 1px solid rgba(220, 220, 220, 0.3); background: rgba(233, 233, 233, 0.3); border-radius: 3px"><h2>Vurox Admin React Theme</h2><h5 style="padding: 0 50px;font-weight:300">Vurox is an amazing theme for bootstrapping new websites for analytics, product management, traffic source checking, you can checkout our new demos and template features from here and there</h5><img src="/image/campaign.png" style="max-width:100%" alt="" /> <p> <a href="" style="padding: 10px 20px;font-size: 16px;text-transform: uppercase;background: rgba(0,0,0,0.5);color: #ddd;font-weight: 700;height: 60px;display: inline-block;line-height: 43px;width: 240px;border-radius: 3px;">Check out more</a> </p></div>',
		time: '13-10-2019 08:23PM',
	},
	{
		ID: 19283792,
		from: 'noreply@laracasts.com',
		isSeen: 1,
		name: 'Laracasts',
		subject: 'Push your web development skills to the next level, through expert screencasts on Laravel, Vue, and so much more',
		desc: '<div class="p-0 p-sm-5" style="text-align:center; border: 1px solid rgba(220, 220, 220, 0.3); background: rgba(233, 233, 233, 0.3); border-radius: 3px"><h2>Vurox Admin React Theme</h2><h5 style="padding: 0 50px;font-weight:300">Vurox is an amazing theme for bootstrapping new websites for analytics, product management, traffic source checking, you can checkout our new demos and template features from here and there</h5><img src="/image/campaign.png" style="max-width:100%" alt="" /> <p> <a href="" style="padding: 10px 20px;font-size: 16px;text-transform: uppercase;background: rgba(0,0,0,0.5);color: #ddd;font-weight: 700;height: 60px;display: inline-block;line-height: 43px;width: 240px;border-radius: 3px;">Check out more</a> </p></div>',
		time: '14-10-2019 08:23PM',
	},
	{
		ID: 19283793,
		from: 'noreply@litmus.com',
		isSeen: 1,
		name: 'Litmus',
		subject: 'Are you getting the most out of your email marketing?',
		desc: '<div class="p-0 p-sm-5" style="text-align:center; border: 1px solid rgba(220, 220, 220, 0.3); background: rgba(233, 233, 233, 0.3); border-radius: 3px"><h2>Vurox Admin React Theme</h2><h5 style="padding: 0 50px;font-weight:300">Vurox is an amazing theme for bootstrapping new websites for analytics, product management, traffic source checking, you can checkout our new demos and template features from here and there</h5><img src="/image/campaign.png" style="max-width:100%" alt="" /> <p> <a href="" style="padding: 10px 20px;font-size: 16px;text-transform: uppercase;background: rgba(0,0,0,0.5);color: #ddd;font-weight: 700;height: 60px;display: inline-block;line-height: 43px;width: 240px;border-radius: 3px;">Check out more</a> </p></div>',
		time: '15-10-2019 08:23PM',
	},
	{
		ID: 19283794,
		from: 'noreply@nimbo-x.com',
		isSeen: 1,
		name: 'Nimbo',
		subject: 'A digital platform to grow and manage your medical practice',
		desc: '<div class="p-0 p-sm-5" style="text-align:center; border: 1px solid rgba(220, 220, 220, 0.3); background: rgba(233, 233, 233, 0.3); border-radius: 3px"><h2>Vurox Admin React Theme</h2><h5 style="padding: 0 50px;font-weight:300">Vurox is an amazing theme for bootstrapping new websites for analytics, product management, traffic source checking, you can checkout our new demos and template features from here and there</h5><img src="/image/campaign.png" style="max-width:100%" alt="" /> <p> <a href="" style="padding: 10px 20px;font-size: 16px;text-transform: uppercase;background: rgba(0,0,0,0.5);color: #ddd;font-weight: 700;height: 60px;display: inline-block;line-height: 43px;width: 240px;border-radius: 3px;">Check out more</a> </p></div>',
		time: '16-10-2019 08:23PM',
	},
	{
		ID: 19283795,
		from: 'noreply@sketchcleaner.com',
		isSeen: 1,
		name: 'Sketch Cleaner',
		subject: 'Sketch plugin that helps you get your design files as clean as a whistle',
		desc: '<div class="p-0 p-sm-5" style="text-align:center; border: 1px solid rgba(220, 220, 220, 0.3); background: rgba(233, 233, 233, 0.3); border-radius: 3px"><h2>Vurox Admin React Theme</h2><h5 style="padding: 0 50px;font-weight:300">Vurox is an amazing theme for bootstrapping new websites for analytics, product management, traffic source checking, you can checkout our new demos and template features from here and there</h5><img src="/image/campaign.png" style="max-width:100%" alt="" /> <p> <a href="" style="padding: 10px 20px;font-size: 16px;text-transform: uppercase;background: rgba(0,0,0,0.5);color: #ddd;font-weight: 700;height: 60px;display: inline-block;line-height: 43px;width: 240px;border-radius: 3px;">Check out more</a> </p></div>',
		time: '17-10-2019 08:23PM',
	},
	{
		ID: 19283796,
		from: 'noreply@later.com',
		isSeen: 1,
		name: 'Later',
		subject: 'Leveraging Artificial Intelligence For Swing Trading Outperformance | Sean McLaughlin',
		desc: '<div class="p-0 p-sm-5" style="text-align:center; border: 1px solid rgba(220, 220, 220, 0.3); background: rgba(233, 233, 233, 0.3); border-radius: 3px"><h2>Vurox Admin React Theme</h2><h5 style="padding: 0 50px;font-weight:300">Vurox is an amazing theme for bootstrapping new websites for analytics, product management, traffic source checking, you can checkout our new demos and template features from here and there</h5><img src="/image/campaign.png" style="max-width:100%" alt="" /> <p> <a href="" style="padding: 10px 20px;font-size: 16px;text-transform: uppercase;background: rgba(0,0,0,0.5);color: #ddd;font-weight: 700;height: 60px;display: inline-block;line-height: 43px;width: 240px;border-radius: 3px;">Check out more</a> </p></div>',
		time: '18-10-2019 08:23PM',
	},
	{
		ID: 19283797,
		from: 'noreply@diggsweep.com',
		isSeen: 1,
		name: 'Diggsweep',
		subject: 'Introducing Creative Market’s Design From Home Bundle!',
		desc: '<div class="p-0 p-sm-5" style="text-align:center; border: 1px solid rgba(220, 220, 220, 0.3); background: rgba(233, 233, 233, 0.3); border-radius: 3px"><h2>Vurox Admin React Theme</h2><h5 style="padding: 0 50px;font-weight:300">Vurox is an amazing theme for bootstrapping new websites for analytics, product management, traffic source checking, you can checkout our new demos and template features from here and there</h5><img src="/image/campaign.png" style="max-width:100%" alt="" /> <p> <a href="" style="padding: 10px 20px;font-size: 16px;text-transform: uppercase;background: rgba(0,0,0,0.5);color: #ddd;font-weight: 700;height: 60px;display: inline-block;line-height: 43px;width: 240px;border-radius: 3px;">Check out more</a> </p></div>',
		time: '19-10-2019 08:23PM',
	},
	{
		ID: 19283798,
		from: 'noreply@koan.com',
		isSeen: 1,
		name: 'Koan',
		subject: '3 Powerful & Enterprise Level Software Apps',
		desc: '<div class="p-0 p-sm-5" style="text-align:center; border: 1px solid rgba(220, 220, 220, 0.3); background: rgba(233, 233, 233, 0.3); border-radius: 3px"><h2>Vurox Admin React Theme</h2><h5 style="padding: 0 50px;font-weight:300">Vurox is an amazing theme for bootstrapping new websites for analytics, product management, traffic source checking, you can checkout our new demos and template features from here and there</h5><img src="/image/campaign.png" style="max-width:100%" alt="" /> <p> <a href="" style="padding: 10px 20px;font-size: 16px;text-transform: uppercase;background: rgba(0,0,0,0.5);color: #ddd;font-weight: 700;height: 60px;display: inline-block;line-height: 43px;width: 240px;border-radius: 3px;">Check out more</a> </p></div>',
		time: '20-10-2019 08:23PM',
	},
	{
		ID: 19283799,
		from: 'noreply@beyondhosting.com',
		isSeen: 1,
		name: 'Beyond Hosting',
		subject: 'State of emergency could be extended; DON’T lie, spread false info about Covid-19',
		desc: '<div class="p-0 p-sm-5" style="text-align:center; border: 1px solid rgba(220, 220, 220, 0.3); background: rgba(233, 233, 233, 0.3); border-radius: 3px"><h2>Vurox Admin React Theme</h2><h5 style="padding: 0 50px;font-weight:300">Vurox is an amazing theme for bootstrapping new websites for analytics, product management, traffic source checking, you can checkout our new demos and template features from here and there</h5><img src="/image/campaign.png" style="max-width:100%" alt="" /> <p> <a href="" style="padding: 10px 20px;font-size: 16px;text-transform: uppercase;background: rgba(0,0,0,0.5);color: #ddd;font-weight: 700;height: 60px;display: inline-block;line-height: 43px;width: 240px;border-radius: 3px;">Check out more</a> </p></div>',
		time: '21-10-2019 08:23PM',
	},
	{
		ID: 19283800,
		from: 'noreply@namastelight.com',
		isSeen: 1,
		name: 'Namaste Light',
		subject: 'Build servers and deploy websites in seconds, not days.',
		desc: '<div class="p-0 p-sm-5" style="text-align:center; border: 1px solid rgba(220, 220, 220, 0.3); background: rgba(233, 233, 233, 0.3); border-radius: 3px"><h2>Vurox Admin React Theme</h2><h5 style="padding: 0 50px;font-weight:300">Vurox is an amazing theme for bootstrapping new websites for analytics, product management, traffic source checking, you can checkout our new demos and template features from here and there</h5><img src="/image/campaign.png" style="max-width:100%" alt="" /> <p> <a href="" style="padding: 10px 20px;font-size: 16px;text-transform: uppercase;background: rgba(0,0,0,0.5);color: #ddd;font-weight: 700;height: 60px;display: inline-block;line-height: 43px;width: 240px;border-radius: 3px;">Check out more</a> </p></div>',
		time: '23-10-2019 08:23PM',
	},
	{
		ID: 19283801,
		from: 'noreply@bannersnack.com',
		isSeen: 1,
		name: 'Bannersnack',
		subject: 'Measure your communications: Know how effective are your emails',
		desc: '<div class="p-0 p-sm-5" style="text-align:center; border: 1px solid rgba(220, 220, 220, 0.3); background: rgba(233, 233, 233, 0.3); border-radius: 3px"><h2>Vurox Admin React Theme</h2><h5 style="padding: 0 50px;font-weight:300">Vurox is an amazing theme for bootstrapping new websites for analytics, product management, traffic source checking, you can checkout our new demos and template features from here and there</h5><img src="/image/campaign.png" style="max-width:100%" alt="" /> <p> <a href="" style="padding: 10px 20px;font-size: 16px;text-transform: uppercase;background: rgba(0,0,0,0.5);color: #ddd;font-weight: 700;height: 60px;display: inline-block;line-height: 43px;width: 240px;border-radius: 3px;">Check out more</a> </p></div>',
		time: '24-10-2019 08:23PM',
	},
]

export const vuroxMail = ( state = initState, action ) => {
	return state
}